#!/usr/bin/env bash
# installs and configure nginx to redirect to anoher page
# creates custom error page
apt-get install  -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/e404_page.html
string_rep="listen 80 default_server;\n\terror_page 404 \/e404_page.html;\n\tlocation = \/e404_page.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_rep/" /etc/nginx/sites-enabled/default
sudo service nginx restart
