#!/usr/bin/env bash
# installs and configure haproxy for 2 servers

# updates the system
sudo apt-get -y update
# installs haproxy
apt-get -y install haproxy

# haproxy config for 2 servers to use roundrobin algorithm
nodes_setting=\
"
frontend  mike_frontend
        bind *:80
        mode http
        default_backend mike_backend
backend mike_backend
        balance roundrobin
        server 129964-web-01 54.173.84.235
        server 129964-web-02 34.207.155.43
"
echo "$nodes_setting" | sudo tee -a /etc/haproxy/haproxy.cfg

# makes init start haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
